version: "3.3"

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: MINT
    container_name: flagright
      # command: uvicorn src.server.app:app --host 0.0.0.0 --port 8000
    command: sleep infinity
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8000:8000"
    networks:
      - dev
    volumes:
      - .:/app

networks:
  dev:
    driver: bridge