version: '3.8'

services:
  web:
    build: .
    container_name: flagrighttask_web
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "8501:8501"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PGDATABASE=${PGDATABASE}
      - PGHOST=${PGHOST}
      - PGPORT=${PGPORT}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - API_KEY=${API_KEY}
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: flagrighttask_db
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
